name: kaz_lab_workshop
channels:
    - conda-forge
dependencies:
    - numpy
    - scipy
    - matplotlib
    - pandas
    - plotnine
    - jupyter
    - xlrd
    - pip:
        - "--editable git+https://github.com/caseygrun/plates.git#egg=plates"
        - "--editable git+https://github.com/mwaskom/seaborn.git#egg=seaborn"