name: kaz_lab_workshop
channels:
    - conda-forge
dependencies:
    - numpy
    - scipy
    - matplotlib
    - pandas
    - plotnine
    - seaborn
    - jupyter
    - xlrd
    - pip:
        - "-e git+https://github.com/caseygrun/plates.git#egg=plates"